diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
user.name=redb
user.email=redb65403@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/redb65403-source/testlast.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.gk-last-accessed=2026-02-06T13:07:27.441Z
branch.main.gk-last-modified=2026-02-06T13:07:29.701Z
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.main.vscode-merge-base=origin/main
branch.t2.vscode-merge-base=origin/main
branch.t2.remote=origin
branch.t2.merge=refs/heads/t3
branch.t2.gk-last-accessed=2026-02-06T12:07:14.625Z
branch.t2.gk-last-modified=2026-02-06T11:50:22.827Z
branch.t2.gk-merge-base=origin/main
branch.t3.remote=origin
branch.t3.merge=refs/heads/t3
branch.t3.vscode-merge-base=origin/t3
branch.t3.gk-merge-base=origin/t3
branch.t1.vscode-merge-base=origin/t3
branch.t1.remote=origin
branch.t1.merge=refs/heads/tt
branch.t1.gk-last-accessed=2026-02-06T12:16:07.701Z
branch.t4.vscode-merge-base=origin/main
branch.t4.remote=origin
branch.t4.merge=refs/heads/t4
branch.t5.vscode-merge-base=origin/t4
branch.t5.remote=origin
branch.t5.merge=refs/heads/t5
branch.t7.vscode-merge-base=origin/t5
branch.t7.remote=origin
branch.t7.merge=refs/heads/t6
branch.t7.gk-last-accessed=2026-02-06T12:30:53.816Z
branch.t7.gk-last-modified=2026-02-06T12:31:37.205Z
user.name=red
user.email=redb65403@gmail.com
